### ISSUE TITLE
Shiny app, Maximum upload size exceeded

### ISSUE THREAD

**Issue by BastienNguyen** [parklab/SigMA#10]
Hi,

What is the maximum upload size allowed for the shiny app?
Even when run locally, it seems that files bigger than 6.5MB cannot be uploaded... 
Is there any way to increase it?

Thanks,

Bastien

**Comment by ranasats** [comment]
Add this to shiny/Server.R:

`options(shiny.maxRequestSize = 15*1024^2)
`

Change "15" to whatever filesize you want, that's ~15MB rightnow

**Comment by dgulhan-bio** [comment]
Once the HMS security requirements is updated and our website is migrated shiny app will allow larger memory.
