### ISSUE TITLE
error when running with do_assign 

### ISSUE THREAD

**Issue by sashagusev** [parklab/SigMA#14]
Hi, I'm able to run a test data of lung cancer mutations with the following command:
```
run(genome_file, 
    data = "msk", 
    do_assign = F, 
    do_mva = F, 
    lite_format = T, 
    check_msi = F, tumor_type = "lung" )
```
which successfully produces a signature output.

However, when I set do_assign to TRUE, I get the following error:
```
You are running SigMA for 2811 Lung Adenocarcinoma(s) sequenced by Targeted Gene Panels
Calculating likelihoods for each cluster
Error in matrix(unlist(value, recursive = FALSE, use.names = FALSE), nrow = nr,  : 
  'data' must be of a vector type, was 'NULL'
Calls: run -> assignment -> Ops.data.frame -> matrix
Execution halted
```

And when I set do_mva to TRUE, the NNLS part finishes but I get the following error:
```
You are running SigMA for 2811 Lung Adenocarcinoma(s) sequenced by Targeted Gene Panels
Calculating likelihoods for each cluster
Calculating cosine similarities
Calculating exposures with NNLS
  |======================================================================| 100%

Predicting MVA score
Error in UseMethod("predict") : 
  no applicable method for 'predict' applied to an object of class "NULL"
Calls: run -> predict_mva -> predict
Execution halted
```

Do you know what could be going on with the inputs that's producing these errors? I'm able to run other cancer types from my data without issue. Thanks for your help!

**Comment by fernandezevn** [comment]
I had this problem as well. The issue is that lung adenocarcinoma is an exploratory cancer type for their model, not a tested model. For the exploratory models, both do_assign and do_mva have to be set to FALSE. Otherwise, it tries to find the proper model based on the cancer type. Since this doesn't exist for lung adenocarcinoma, it returns NULL.

**Comment by sashagusev** [comment]
Thank you, this is very helpful, and totally obvious in retrospect.
