### ISSUE TITLE
the procedure to get the characteristics and train the machine learning

### ISSUE THREAD

**Issue by ccx555** [parklab/SigMA#21]
hello,
I would like to apply this method to other cancers, but I found that there is no procedure to get the characteristics and train the machine learning, I wonder if it is possible to provide.
And I have another question, is the feature of panel directly used WGS?
My email address is hhppccx@126.com.
thank you.

**Comment by TracyYXChen** [comment]
My two cents:
1) You don't need to train the model from scratch, as SigMA already has pretrained clusters. The only thing you need to do is to provide the cancer type and the sequencing platform, panel or WGS/WXS.
2) Yes, for panel data, SigMA used pretrained information from WGS data.

**Comment by dgulhan-bio** [comment]
There is some information here 
https://github.com/parklab/SigMA/wiki/Optimize
Also you can checkout the [example](https://github.com/parklab/SigMA/blob/master/examples/test_tune_example.R) script.

**Comment by dgulhan-bio** [comment]
I added more info here:
https://github.com/parklab/SigMA/wiki/Training-a-new-model
