### ISSUE TITLE
COSMIC version 3 mutational signatures

### ISSUE THREAD

**Issue by EmreKocakavuk** [parklab/SigMA#22]
Thanks for making this package available. I was wondering whether the approach you are using could be applied to the new version of COSMIC mutational signatures, especially to the newly defined double base substitution (DBS) and indel (ID) signatures. 

Thanks, Emre

**Comment by dgulhan-bio** [comment]
Hi Emre,
As you said the algorithm is using Cosmic v2 SBS signatures. The approach can be applied to any types of signatures (DBS and ID). However to do so, we need to calculate clusters in WGS data which serve as reference distributions for smaller sequencing platforms, and tune gradient boosting classifiers. We will inform you when this becomes available.
Best,
Doga
