### ISSUE TITLE
Question: Usage of SigMA with data from new panel

### ISSUE THREAD

**Issue by lasseringstedmark** [parklab/SigMA#33]
Hi, 

I would like to use SigMA with some research data obtained with another panel than the MSK-IMPACT and FoundationOne.

When looking into the documentation, it is not clear to me if this actually can be done by the pre-trained clusters or new clusters needs to be calculated. 

I hope you can help me clarify this.

Thanks in advance.

**Comment by TracyYXChen** [comment]
As a SigMA user, here are my two cents: if you use SigMA, then it means you believe pre-trained clusters can solve your problem (actually they can at most times). Currently, SigMA doesn't support train your own clusters.

**Comment by dgulhan-bio** [comment]
You can train a model following this [example](https://github.com/parklab/SigMA/blob/master/examples/test_tune_example.R)
Checkout the wiki as well:
https://github.com/parklab/SigMA/wiki/Optimize
You can

**Comment by dgulhan-bio** [comment]
I added more info here
https://github.com/parklab/SigMA/wiki/Training-a-new-model
