### ISSUE TITLE
SigMA Webtool

### ISSUE THREAD

**Issue by ThibautMatis** [parklab/SigMA#34]
Hi,

I'm not an expert in coding, so I'm really interested in SigMA webtool. Thus, I used breast cancer normal-paired VCF from Mutect2, then I launched SigMA. The prob is there is a pop up with "Calculation in progress", and I waited for 2h without results whereas my VCF contains only 20 mutations. 
Is it normal? 

Thank you in advance for your help

**Comment by worker000000** [comment]
It is the same for me, maybe the sever is broken, so I use the r script

**Comment by dgulhan-bio** [comment]
This is issue has been fixed.
