### ISSUE TITLE
WGS?

### ISSUE THREAD

**Issue by alhafidzhamdan** [parklab/SigMA#35]
Hi there can SigMA be run on WGS samples?

**Comment by ipstone** [comment]
It can be specified in the run function parameter as : 

```
run(genome_file, 
    **data = "wgs",** 
    do_assign = T, 
    do_mva = T, 
    lite_format = T, 
    check_msi = T)
```


- you can find the details in the documentation: https://github.com/parklab/SigMA/blob/master/manual_sigma.pdf
