### ISSUE TITLE
Question about `Signature_3_l_rat` threshold?

### ISSUE THREAD

**Issue by ipstone** [parklab/SigMA#36]
Hi, thanks for the great job on SigMA.

I am testing out SigMA on my experimental samples, regarding Signature_3_I_rat:
``` 
Signature_3_l_rat is the likelihood ratio of the NNLS decomposition with
Signature 3 considering the possibility of an alternative decompositions
without Signature 3. A value of 0.5 indicate that an NNLS decomposition
without Signature 3 is as likely.

```

The definition note in the wiki is not very clear to me. If a value 0.5 indicate likely, what about value of 1? 

- Does it mean more likely to be decomposed with signature 3 than a value of 0.5?
or Does it mean more likely to be decomposed without sigantgure 3 than a value of 0.5?

Thanks a lot in advance!

**Comment by worker000000** [comment]
mean more likely to be decomposed without sigantgure 3 than a value of 0.5. I guess

**Comment by ipstone** [comment]
as I am reading again, I think this value as stated meaning likelihood ratio to be decomposed to Signature 3. Then 0.5 would mean half/half, so when it's 0.5, it means unlikely signature 3.

When the value is 1, then it's 100 percent signature 3 then. - hoping I am reading it correctly.

**Comment by dgulhan-bio** [comment]
Signature_3_l_rat indicates:
`(probability decomposition with Sig3)/(probability decomposition with Sig3 + probability decomposition without Sig3)`

A value of 0.5 indicates that the mutations can be decomposed equally well with other signatures in the catalog, and a value above this value indicates that the decomposed spectrum better explains the mutations if Sig3 is used in the decomposition. 

To determine a threshold you can run the tuning example code for your dataset and this creates a file `<input_file_name>simulation_predictions.csv`. Using this file you can check the false positive rates with different thresholds on each variable. The file has a `is_sig3` column this is sig3 status in WGS. Then you can see how many Sig3+ samples fall above your threshold and how many Sig3- samples fall above your threshold on Signature_3_l_rat values.

`Signature_3_c*_ml` columns indicate the likelihood of Sig3+ clusters in WGS data. If you run in the lite mode you will find get a `Signature_3_ml` column which is the sum of all the `Signature_3_c*_ml` values. This indicates how likely the sample is to match to a Sig3+ cluster in WGS. This value is independent from NNLS calculation, so it can also be helpful.

**Comment by beginner984** [comment]
Sorry what if for two samples I have


Signature_3_ml
--
0.6834465
1.20E-07

Which one is sig3+

**Comment by dgulhan-bio** [comment]
> Sorry what if for two samples I have
> 
> ## Signature_3_ml
> 0.6834465
> 1.20E-07
> 
> Which one is sig3+

Depends on the dataset. I added some info in FAQ section on the wiki.
