### ISSUE TITLE
The interpretation of the results

### ISSUE THREAD

**Issue by beginner984** [parklab/SigMA#39]
Sorry 

I have run SigMA on the example .vcf

From the output how I know if the sample is Signature 3 + or not? Which column of the results please? Any threshold?

Also when I changed the code for cancer of my interest, I got this error

```
> run(genome_file, 
+     data = "wgs", 
+     do_assign = F, 
+     do_mva = F,
+     tumor_type = 'Oesophageal Carcinoma', 
+     lite_format = F,add_sig3 = T)
You are running SigMA for 2 (s) sequenced by Whole Genome Sequencing
Calculating likelihoods for each cluster
 Error in colSums(signatures) : 
  'x' must be an array of at least two dimensions 
>  

```
Thank you

**Comment by dgulhan-bio** [comment]
Tumor type should be 'eso'. You can set do_mva = T and lite_format = T. Then in the output file check the categ column. Did you take a look at the wiki? https://github.com/parklab/SigMA/wiki/
