### ISSUE TITLE
Running new model on my data

### ISSUE THREAD

**Issue by MaryGoAround** [parklab/SigMA#40]
Hello

In trying new model, you mentioned we should replace
```
data_dir <- system.file("extdata/matrices/matrices_96dim.rda", package="SigMA")
load(data_dir)

tumor_type <- 'breast'
remove_msi_pole <- F

m <- matrices_96dim[['tcga']][[tumor_type]]

write.table(m, 'tmp.csv', row.names = F, sep = ',', quote = F)
input_file <- 'tmp.csv'
```
With my own data which are .vcf files

```
input_file <- <path_to_your_local_input>
tumor_type <- tumor_type> # tumor_type for your dataset
remove_msi_pole <- T # F if you are certain there are no mismatch repair deficient or POLE-exo mutated tumors in your da
```

Using lines 1-21 in test.R I get `genomes `and `genomes_matrix` as output. When I got to the next step

```
data_val <- find_data_setting(input_file, 
  "breast",  
  remove_msi_pole =T)
```
I don't know what I should put instead of input_file because when I try genomes_matrix says 

```
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  'file' must be a character string or connection 
```

How I can convert my .vcf files to a compatible input for `test_determine_cutoff_mine.R` please ?

Thank you for any help

**Comment by dgulhan-bio** [comment]
The input file should contain the matrix of mutational spectra, you can generate it using the make_matrix function from your vcf files. 
```

m <- make_matrix(<path_to_vcf_dir>, file_type = 'vcf', ref_genome_name = 'hg19')
df <- conv_snv_matrix_to_df(m)
write.table(df, file = <path_to_matrix_file>, row.names = F, sep = ',', quote = F)
input_file <- <path_to_matrix_file>
```
You can continue the example script from here.
