### ISSUE TITLE
Getting this error in SigMA

### ISSUE THREAD

**Issue by beginner984** [parklab/SigMA#41]
Hello

I don't know why I get this error

```
> run(genome_file, 
+     data = "wgs", 
+     do_assign = T, 
+     do_mva = F,
+     tumor_type = 'eso', 
+     lite_format = F)
Error in run(genome_file, data = "wgs", do_assign = T, do_mva = F, tumor_type = "eso",  : 
  could not find function "run"
```

**Comment by ZKai0801** [comment]
looks like you didn't load the package in advance. Try to run:
```
devtools::load_all("/path/to/your/sigma/directory/")
```

**Comment by beginner984** [comment]
Thank you so much extremly helpful

Sorry from the results, which of my samples are sig3+

I read the instruction but really I could not follow that properly

[results.txt](https://github.com/parklab/SigMA/files/5670059/results.txt)

This is what I see


Signature_3_l_rat
--
0.625647036
0.5

So the first sample is + because the number is  > 0.5 , right?
