### ISSUE TITLE
test_determine_cutoff doesn't work

### ISSUE THREAD

**Issue by romagnolid** [parklab/SigMA#42]
It seems the file `data_dir <- system.file("extdata/matrices/matrices_96dim.rda", package="SigMA")` has been changed and now the line 
`m <- matrices_96dim[['tcga']][[tumor_type]]`
returns an error (there's no `tcga` element in the list).

This makes quite difficult to understand how to run the script.

**Comment by dgulhan-bio** [comment]
Thanks for letting me know, this was due to a change in matrices_96dim that was not propagated to the test script.
