### ISSUE TITLE
Error in colSums(signatures)

### ISSUE THREAD

**Issue by deb0612** [parklab/SigMA#51]
Dear sir,
When I execute run( )function as following:
<run(genome_file, data = "seqcap", do_assign = T, do_mva = F, tumor_type = 'Panc_ad', lite_format = F)>
You are running SigMA for 1 (s) sequenced by Whole Exome Sequencing 37 Mb
Calculating likelihoods for each cluster

Error in colSums(signatures) : 
  'x' must be an array of at least two dimensions 

4. stop("'x' must be an array of at least two dimensions") 
3.colSums(signatures) at run.R#278
2.t(t(signatures)/colSums(signatures)) at run.R#278
1.run(genome_file, data = "seqcap", do_assign = T, do_mva = F, 
    tumor_type = "Panc_ad", lite_format = F)

**Comment by dgulhan-bio** [comment]
Could you try tumor_type "panc_ad"?
