### ISSUE TITLE
Training new model on my sequencing platform

### ISSUE THREAD

**Issue by Tim0thy1** [parklab/SigMA#54]
Hi,

there can SigMA be run on custom panel?

I have a maf  obtained with another panel sequencing.  How can I build a new model?

####code in test_tune_example.R #####
devtools::load_all()

m <- make_matrix(my_maf_file, file_type='maf', ref_genome_name = 'hg19')
df <- conv_snv_matrix_to_df(m)

file_name <- 'XXX.csv'
tumor_type <- 'XXX'   ###not breast
write.table(df, file_name, row.names = F, sep = ',', quote = F)

output_file_built_in <- run(file_name,
                            data = '????????',
                            tumor_type = tumor_type, 
                            do_mva = T,
                            do_assign = T,
                            check_msi = T)

Are we have to choose a data option which selects the built in model?

**Comment by dgulhan-bio** [comment]
Please take a look at the two sections in wiki under Optimizing SigMA for your dataset section:
https://github.com/parklab/SigMA/wiki
If you have any issues during the process please open a new ticket.
