### ISSUE TITLE
plot_summary does not take into account different platforms 

### ISSUE THREAD

**Issue by lbeltrame** [parklab/SigMA#57]
Any run generated with something that's not `msk` or `wgs` or `seqcap` platforms can't be plotted, because the code only accounts for the existence of these:

```r
    msk_string <- gsub(platform_names[["msk"]], pattern = " ",
        replace = "")
    exome_string <- gsub(platform_names[["seqcap"]], pattern = " ",
        replace = "")
    wgs_string <- gsub(platform_names[["wgs"]], pattern = " ",
        replace = "")
    tumor_type <- unlist(strsplit(unlist(strsplit(file, split = "tumortype_"))[[2]],
        split = "_platform_"))[[1]]
    platform <- unlist(strsplit(unlist(strsplit(file, split = "platform_"))[[2]],
        split = "_cf"))[[1]]
    if (platform == msk_string)
        data = "msk"
    if (platform == exome_string)
        data = "seqcap"
    if (platform == wgs_string)
        data = "wgs"
```

Since `data` is also a function in R which, by pure chance, is masked by the code, if the platform is not one of these, the user receives a clearly bogus error:

`Error in cutoffs_strict[[data]] : invalid subscript type 'closure'`

**Comment by dgulhan-bio** [comment]
This function was mainly written for the shiny app this is why it was working for built-in data settings and was outdated. It is now updated. You can now run it with a custom model directly using the automatic output file or if you want to rename your output file as something else you can also set the data and tumor_type parameters in the plot_summary function.
 Please see instructions on the wiki for training a new model for your panel.
 
 https://github.com/parklab/SigMA/commit/c065a5ce182d0a5aeccd2123c7fcbe0cc28fba02
