### ISSUE TITLE
make_matrix error

### ISSUE THREAD

**Issue by BastienNguyen** [parklab/SigMA#6]
Dear,

I am trying to run the test_maf.R but it throws an error at the very first step when it tries to do make_matrix (see below);

`genomes_matrix <- make_matrix(directory = data_dir, file_type = 'maf')`
`Error in rownames<-(*tmp*, value = c("chr17", "chr12", "chr22", "chr1",  : 
  invalid rownames length `

I also tried this;
`genomes_matrix <- make_matrix(directory = data_dir, file_type = 'custom', chrom_colname = 'Chromosome', pos_colname = 'Start_Position',ref_colname =  'Reference_Allele', alt_colname = 'Tumor_Seq_Allele2', ncontext = 3, nstrand=1, ref_genome = BSgenome.Hsapiens.UCSC.hg19)`

But it throws the same error.

Could you please comment on this?

Thanks,

Bastien

**Comment by dgulhan-bio** [comment]
A very long time has passed if this issue is still unresolved please open a new issue. I will close this one.
