### ISSUE TITLE
arguments imply differing number of rows

### ISSUE THREAD

**Issue by YingYa** [parklab/SigMA#60]
When a sample without 'INS' or 'DEL', the 'make_table_indel_repeat.R' will be failed to run.

Error in data.frame(nmsi_ins = c(unlist(t_ins)), nmsi_del = c(unlist(t_del)),  :
  arguments imply differing number of rows: 1062, 1063

**Comment by dgulhan-bio** [comment]
I am not getting this error, so I am not sure but I think this should solve it:
https://github.com/parklab/SigMA/commit/2c805f7f2785a0e0dcb3c8b1f525f5b805f9788a
Thanks
