### ISSUE TITLE
MAF Column Issues

### ISSUE THREAD

**Issue by fernandezevn** [parklab/SigMA#7]
Hello,

It looks like there are some issues with the column names for MAFs. There are options for make_matrix that allow you to specify specific column names, however it looks like the arguments aren't implemented in the code anywhere.

There is also a column name issue in .make_vector_from_maf. identical() is used to decide if tumor_seq_allele1 or tumor_seq_allele2 should be used, however these columns are read in as factors. All values in the two columns can be identical for a sample, but the possible factor levels can differ. With identical(), it will return false if there are different available factor levels, even if the present values are identical. 

These issues caused me to get an output of all 0s, causing an error further downstream when running my MAFs.

**Comment by dgulhan-bio** [comment]
Thanks for reporting the issue related to Tumor_Seq_Allele columns being factors, we didn't run into this issue but others might have. Here is a PR converting the columns to character: https://github.com/parklab/SigMA/pull/27.

To use custom column names set file_type to 'custom'. To use this, remove indels, store each sample in a separate file and put them in an input directory:
 m <- make_matrix(directory = <path_to_your_directory>,
                                file_type = 'custom,
                                chrom_colname = <your_choice_of_chrom_colname>, 
                                pos_colname = <your_choice_of_position_colname>,
                                alt_colname = <your_choice_of_alt_allele_colname>, 
                                ref_colname = <your_choice_of_ref_allele_colname>)
